Repository camunda/connectors, pull requests merged in 2023-07, with the labels that each got.

#850 fix(inbound): silently skip elements that are not connectors
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
Labels: kind:bug

#871 fix kafka value serialization; change group id property to include elementId and processDefinitionKey
  connectors/kafka/pom.xml
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunction.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/outbound/KafkaConnectorFunctionTest.java
Labels: kind:bug

#889 fix: filter inbound eligible elements before performing 'sanity check'
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
Labels: kind:bug

#756 feat: get and verify jwt token in webhook connector
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/FeelParserWrapper.java
  connectors/webhook/element-templates/webhook-connector-intermediate.json
  connectors/webhook/element-templates/webhook-connector-start-event.json
  connectors/webhook/pom.xml
  connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/authorization/JWTChecker.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/model/JWTProperties.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/JWTCheckerTest.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/JWTIntegrationTest.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/TestWebhookProcessingPayload.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/utils/TestRSAKeyProvider.java
  connectors/webhook/src/test/resources/authorization/__files/jwks.json
  pom.xml
Labels: kind:enhancement

#896 Jackson module for FEEL expressions
  connector-runtime/connector-runtime-core/pom.xml
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/FeelConnectorFunctionProvider.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/FeelEngineWrapper.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/FeelEngineWrapperException.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/jackson/FeelFunctionDeserializer.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/jackson/FeelSupplierDeserializer.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/feel/jackson/JacksonModuleFeelFunction.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/feel/FeelEngineWrapperExpressionEvaluationTest.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/feel/jackson/FeelFunctionDeserializerTest.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/feel/jackson/FeelSupplierDeserializerTest.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandlerTest.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/MeteredInboundCorrelationHandler.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/authorization/JWTChecker.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookConnectorProperties.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/utils/ObjectMapperSupplier.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/JWTCheckerTest.java
  pom.xml
Labels: scope:runtime

#895 fix: use ExecutorService instead of default ForkJoinPool
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
Labels: kind:bug
