Repository camunda/connectors, pull requests merged in 2023-04, with the labels that each got.

#422 Remove all ending dots in `description` property values
  connectors/power-automate/element-templates/power-automate-connector.json
Labels: scope:powerautomate

#435 fix(docs): Property `queue.messageGroupId` is required for FIFO queues.
  connectors/sqs/element-templates/aws-sqs-connector.json
Labels: kind:documentation

#390 chore(asana): introduce Asana protocol connector
  connectors/asana/LICENSE.txt
  connectors/asana/README.md
  connectors/asana/element-templates/asana-connector.json
Labels: hackathon
