Repository camunda/connectors, pull requests merged in 2024-07, with the labels that each got.

#2804 Google Sheets Connector: Adding a worksheet will return the properties of the worksheet
  connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/GoogleSheetOperation.java
  connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/operation/impl/CreateWorksheetOperation.java
  connectors/google/google-sheets/src/test/java/io/camunda/connector/gsheets/operation/impl/CreateWorksheetOperationTest.java
Labels: backport release/8.5

#2814 fix(rest): Properly handle null Content-Type header
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestHeadersBuilder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.6

#2821 fix(twilio): Fix content-type header issue when the case is inconsistent + fix element template
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestHeadersBuilder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
  connectors/twilio/element-templates/twilio-connector.json
Labels: backport release/8.6

#2823 fix(rest): Fix missing path encoding in URLs
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.6

#2826 fix(rest): Ensure proper URL encoding + fix case issues with content type headers
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestUriBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.6

#2815 chore(spring-zeebe) bump version of spring zeebe to 8.5.7
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/secret/ConsoleSecretProviderTest.java
  parent/pom.xml
Labels: backport release/8.5

#2852 fix(kafka): Handle consumerGroup properly + update the offset override part
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java
  bundle/default-bundle/src/test/resources/application-docker-core.properties
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/OffsetUpdateRequiredListener.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/integration/KafkaIntegrationTest.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5
