Repository camunda/connectors, pull requests merged in 2024-08, with the labels that each got.

#3012 fix(aws-bedrock): small fixes on the element templates
  connectors/aws/aws-bedrock/element-templates/aws-bedrock-outbound-connector.json
  connectors/aws/aws-bedrock/element-templates/hybrid/aws-bedrock-outbound-connector-hybrid.json
  connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/model/ConverseData.java
  connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/model/InvokeModelData.java
Labels: backport release/8.6

#3016 fix(slack) increase the version of the element template
  connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
  connectors/slack/element-templates/slack-outbound-connector.json
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
Labels: backport release/8.6

#3018 fix(kafka): close consumer before retrying on failures
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#3080 fix(core) rest connector inbound was not working with query params
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/resources/webhook_connector.bpmn
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#3135 fix(rabbitmq): unnecessary unescaping in inbound connector
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java
Labels: backport release/8.3, backport release/8.4

#3189 ci(integration): use unique id to allow parallel Helm test runs, accept more commit types
  .github/workflows/INTEGRATION_TEST.yml
  .github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml
Labels: backport release/8.3, backport release/8.4, backport release/8.5

#3210 fix(rest): Fix readTimeout for old runtimes before 8.5
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/model/HttpCommonRequestTest.java
Labels: backport release/8.6

#3212 other(GHA): Add a check ensuring a PR has a milestone or the NO MILESTONE label
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/PULL_REQUEST_MILESTONE_VALID.yml
Labels: no milestone
