Repository camunda/connectors, pull requests merged in 2024-09, with the labels that each got.

#3254 feature: log inbound context log to logger
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
Labels: no milestone

#3242 feat(element-template-generator): accept yaml content as parameter in template generator
  element-template-generator/openapi-parser/pom.xml
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiGenerationSource.java
  element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
  element-template-generator/openapi-parser/src/test/resources/example.yaml
  element-template-generator/postman-collections-parser/pom.xml
  element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/PostmanCollectionsGenerationSource.java
  element-template-generator/postman-collections-parser/src/test/java/io/camunda/connector/generator/postman/PostmanCollectionsGeneratorDryRunExampleTest.java
  element-template-generator/postman-collections-parser/src/test/resources/example.yaml
Labels: no milestone

#3281 fix(rabbitmq): consumer retry loop
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5

#3288 chore(inbound): Set the readiness to True when starting
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5

#3302 other(renovate): add no milestone label, include release 8.6
  renovate.json
Labels: backport release/8.6, no milestone

#3309 ci(release): enable force push to protected release branches
  .github/workflows/RELEASE.yaml
Labels: backport release/8.6, no milestone

#3316 other(readme): fix spotless error
  connectors/http/rest/README.md
Labels: backport release/8.6

#3324 fix(postman): replacement pr for 3322_NPE_when_empty_path_in_postman_collection
  element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/utils/PostmanPathUtil.java
Labels: no milestone

#3325 other(codeowners): exclude files Renovate often updates
  CODEOWNERS
Labels: no milestone

#3330 chore(kafka): Fix bindings for Avro schema
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-outbound-connector-hybrid.json
  connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
  connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
  connectors/kafka/element-templates/kafka-inbound-connector-start-message.json
  connectors/kafka/element-templates/kafka-outbound-connector.json
  connectors/kafka/src/main/java/io/camunda/connector/kafka/model/schema/AvroInlineSchemaStrategy.java
Labels: backport release/8.6

#3340 ci(release): enable force push to protected release branches
  .github/workflows/RELEASE.yaml
Labels: no milestone

#3358 chore(tool-versions): use current Java, Maven versions
  .tool-versions
  README.md
Labels: no milestone

#3356 ci(release): use force-with-lease when pushing
  .github/workflows/RELEASE.yaml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone

#3357 other(codeowners): exclude files Renovate often updates (#3325)
  CODEOWNERS
Labels: no milestone

#3366 fix(sqs): remove pattern validation in runtime, add override description to template
  connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java
Labels: backport release/8.6

#3377 ci(backport-pr): use protected branch PAT
  .github/workflows/BACKPORT_PR.yml
Labels: backport release/8.6, no milestone

#3380 ci(release): revert to force pushing release tag
  .github/workflows/RELEASE.yaml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone

#3384 chore(spotless): remove .md spotless checks
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone

#3381 fix(email-connector): proposition to mitigate the issue of deletion
  connectors/email/element-templates/email-inbound-connector-boundary.json
  connectors/email/element-templates/email-inbound-connector-intermediate.json
  connectors/email/element-templates/email-message-start-event-connector.json
  connectors/email/element-templates/email-outbound-connector.json
  connectors/email/element-templates/hybrid/email-inbound-connector-boundary-hybrid.json
  connectors/email/element-templates/hybrid/email-inbound-connector-intermediate-hybrid.json
  connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
  connectors/email/element-templates/hybrid/hybrid-email-message-start-event-connector-hybrid.json
  connectors/email/pom.xml
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/JakartaEmailListener.java
  connectors/email/src/main/java/io/camunda/connector/email/inbound/EmailConnectorExecutable.java
  connectors/email/src/main/java/io/camunda/connector/email/inbound/model/EmailInboundConnectorProperties.java
  connectors/email/src/main/java/io/camunda/connector/email/inbound/model/EmailListenerConfig.java
  connectors/email/src/main/java/io/camunda/connector/email/inbound/model/HandlingStrategy.java
  connectors/email/src/main/java/io/camunda/connector/email/inbound/model/InitialPollingConfig.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/Pop3DeleteEmail.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/Pop3ReadEmail.java
  connectors/email/src/main/resources/META-INF/services/io.camunda.connector.api.inbound.InboundConnectorExecutable
  connectors/http/rest/README.md
Labels: backport release/8.6

#3394 fix(email-connector): send emails will always make the process fail
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/JakartaEmailActionExecutor.java
Labels: backport release/8.6
