Repository camunda/connectors, pull requests merged in 2024-05, with the labels that each got.

#2402 fix(saas): apply new operate config
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/TestSpringContextStartup.java
Labels: backport release/8.5, backport release/8.6

#2442 fix(webhook): incorrect type check resulting in missing return data
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java
Labels: backport release/8.6

#2434 fix(deps): update version.spring-zeebe to v8.5.2 (#2255)
  parent/pom.xml
Labels: support

#2502 feat(jdbc): Remove MySQL ConnectorJ and use MariaDb instead
  connectors/jdbc/pom.xml
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/SupportedDatabase.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionStringHelper.java
  connectors/jdbc/src/test/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelperTest.java
Labels: backport release/8.6

#2508 fix(jdbc): Fix invalid Javadoc comment
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java
Labels: backport release/8.6

#2513 feat(jdbc): Don't use URI as it breaks when using the hash char
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionHelper.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelper.java
  connectors/jdbc/src/test/java/io/camunda/connector/jdbc/utils/ConnectionParameterHelperTest.java
Labels: backport release/8.6

#2515 fix(jdbc): Remove the JDBC Connector from the bundle and release
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json
  connectors/jdbc/element-templates/jdbc-outbound-connector.json
  connectors/pom.xml
Labels: backport release/8.6

#2635 feat(sqs, kafka): enable acknowledgment config
  connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
  connectors/aws/aws-sqs/pom.xml
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-boundary-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-intermediate-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-event-hybrid.json
  connectors/kafka/element-templates/hybrid/kafka-inbound-connector-start-message-hybrid.json
  connectors/kafka/element-templates/kafka-inbound-connector-boundary.json
  connectors/kafka/element-templates/kafka-inbound-connector-intermediate.json
  connectors/kafka/element-templates/kafka-inbound-connector-start-event.json
  connectors/kafka/element-templates/kafka-inbound-connector-start-message.json
  connectors/kafka/pom.xml
Labels: scope:sqs, scope:kafka, scope:element-template

#2651 ci: adjust branch detection
  .github/workflows/RELEASE.yaml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#2612 Helm integration tests for release branches
  .github/workflows/INTEGRATION_TEST.yml
  .github/workflows/helm-git-refs.json
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#2674 ci: rollback target commitish change in the release workflow
  .github/workflows/RELEASE.yaml
Labels: backport release/8.6

#2675 Element Template generation: set notEmpty: false explicitly
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/FieldProcessor.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/JakartaValidationFieldProcessor.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java
Labels: backport release/8.5
