Repository camunda/connectors, pull requests merged in 2024-12, with the labels that each got.

#3645 feat(email-connector): add document handling to the email connector
  connectors/email/element-templates/email-outbound-connector.json
  connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
  connectors/email/src/main/java/io/camunda/connector/email/client/EmailActionExecutor.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/EmailConnectorFunction.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java
  connectors/email/src/main/java/io/camunda/connector/email/response/ReadEmailResponse.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/TestImapMessage.java
  connectors/email/src/test/resources/img/img.png
Labels: component:qa, deploy-preview, qa:required

#3549 feat(gemini): implement Google Gemini connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/google/google-base/src/main/java/io/camunda/google/supplier/util/GoogleServiceSupplierUtil.java
  connectors/google/google-drive/element-templates/google-drive-outbound-connector.json
  connectors/google/google-drive/element-templates/hybrid/google-drive-outbound-connector-hybrid.json
  connectors/google/google-gemini/element-templates/google-gemini-outbound-connector.json
  connectors/google/google-gemini/element-templates/hybrid/google-gemini-outbound-connector-hybrid.json
  connectors/google/google-gemini/pom.xml
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/GeminiConnectorFunction.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/caller/GeminiCaller.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/mapper/FunctionDeclarationMapper.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/mapper/GenerativeModelMapper.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/mapper/PromptsMapper.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/model/BlockingDegree.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/model/GeminiRequest.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/model/GeminiRequestData.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/model/ModelVersion.java
  connectors/google/google-gemini/src/main/java/io/camunda/connector/gemini/supplier/VertexAISupplier.java
  connectors/google/google-gemini/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/google/google-gemini/src/main/resources/icon.svg
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/GeminiConnectorFunctionTest.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/TestUtil.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/caller/GeminiCallerTest.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/mapper/FunctionDeclarationMapperTest.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/mapper/GenerativeModelMapperTest.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/mapper/PromptsMapperTest.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/supplier/VertexAISupplierTest.java
  connectors/google/google-gemini/src/test/resources/correct_function_call.json
  connectors/google/google-gemini/src/test/resources/fully_filled_model.json
  connectors/google/google-gemini/src/test/resources/incorrect_function_call.json
  connectors/google/google-gemini/src/test/resources/only_required_fields_model.json
  connectors/google/google-gemini/src/test/resources/prompts.json
  connectors/google/google-gemini/src/test/resources/prompts_with_empty_entry.json
  connectors/google/google-gemini/src/test/resources/prompts_with_null_entry.json
  connectors/google/google-gemini/src/test/resources/prompts_with_wrong_value_type.json
  connectors/google/google-sheets/element-templates/google-sheets-outbound-connector.json
  connectors/google/google-sheets/element-templates/hybrid/google-sheets-outbound-connector-hybrid.json
  connectors/google/pom.xml
Labels: deploy-preview, qa:required

#3762 fix(document): enable Camunda document store
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/InMemoryDocumentStoreConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
  connector-sdk/document/src/main/java/io/camunda/document/CamundaDocument.java
  connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/DocumentReferenceModel.java
  connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentSerializationTest.java
  connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/app/TestConnectorRuntimeApplication.java
  connectors-e2e-test/connectors-e2e-test-base/src/main/resources/application.properties
Labels: no milestone

#3770 docs(readme): Fix all the broken documentation links
  connectors/README.md
  connectors/aws/aws-dynamodb/README.md
  connectors/aws/aws-eventbridge/README.md
  connectors/aws/aws-lambda/README.md
  connectors/aws/aws-sns/README.md
  connectors/aws/aws-sqs/README.md
  connectors/google/google-drive/README.md
  connectors/http/graphql/README.md
  connectors/http/rest/README.md
  connectors/http/rest/README.peb
  connectors/jdbc/README.md
  connectors/kafka/README.md
  connectors/microsoft-teams/README.md
  connectors/rabbitmq/README.md
  connectors/sendgrid/README.md
  connectors/slack/README.md
Labels: kind:documentation

#3466 chore(element-templates): Update element template descriptions and add keywords
  connectors/asana/element-templates/asana-connector.json
  connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/AutomationAnywhereConnector.java
  connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/BedrockConnectorFunction.java
  connectors/aws/aws-dynamodb/src/main/java/io/camunda/connector/aws/dynamodb/AwsDynamoDbServiceConnectorFunction.java
  connectors/aws/aws-eventbridge/src/main/java/io/camunda/connector/aws/eventbridge/EventBridgeFunction.java
  connectors/aws/aws-lambda/src/main/java/io/camunda/connector/awslambda/LambdaConnectorFunction.java
  connectors/aws/aws-sagemaker/src/main/java/io/camunda/connector/sagemaker/SagemakerConnectorFunction.java
  connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/inbound/SnsWebhookExecutable.java
  connectors/aws/aws-sns/src/main/java/io/camunda/connector/sns/outbound/SnsConnectorFunction.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/outbound/SqsConnectorFunction.java
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/TextractConnectorFunction.java
  connectors/blue-prism/element-templates/blue-prism-connector.json
  connectors/easy-post/element-templates/easy-post-connector.json
  connectors/email/element-templates/email-inbound-connector-boundary.json
  connectors/email/element-templates/email-inbound-connector-intermediate.json
  connectors/email/element-templates/email-message-start-event-connector.json
  connectors/email/element-templates/email-outbound-connector.json
  connectors/email/element-templates/hybrid/email-inbound-connector-boundary-hybrid.json
  connectors/email/element-templates/hybrid/email-inbound-connector-intermediate-hybrid.json
  connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
  connectors/email/element-templates/hybrid/hybrid-email-message-start-event-connector-hybrid.json
  connectors/email/src/main/java/io/camunda/connector/email/inbound/EmailConnectorExecutable.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/EmailConnectorFunction.java
  connectors/github/element-templates/github-connector.json
  connectors/github/element-templates/github-webhook-connector-boundary.json
  connectors/github/element-templates/github-webhook-connector-intermediate.json
  connectors/github/element-templates/github-webhook-connector-message-start.json
  connectors/github/element-templates/github-webhook-connector-start-event.json
  connectors/gitlab/element-templates/gitlab-connector.json
  connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveFunction.java
  connectors/google/google-sheets/element-templates/google-sheets-outbound-connector.json
  connectors/google/google-sheets/element-templates/hybrid/google-sheets-outbound-connector-hybrid.json
  connectors/google/google-sheets/src/main/java/io/camunda/connector/gsheets/GoogleSheetsFunction.java
  connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json
  connectors/jdbc/element-templates/jdbc-outbound-connector.json
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/outbound/JdbcFunction.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/ElementTemplate.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/ElementTemplateBuilder.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedDocsGenerator.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/ElementTemplate.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/ElementTemplateSerializationTest.java
  element-template-generator/core/src/test/resources/test-element-template.json
Labels: no milestone

#3797 chore(properties): fix applicaiton properties
  bundle/default-bundle/src/test/resources/application.properties
Labels: no milestone

#3796 fix(mail-connector): check htmlBody and/or body is null and throw an error
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java
  connectors/email/src/test/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmailTest.java
Labels: backport release/8.6

#3744 feature(aws-s3-connector): AWS s3 connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/aws/aws-s3/element-templates/aws-s3-outbound-connector.json
  connectors/aws/aws-s3/element-templates/hybrid/aws-s3-outbound-connector-hybrid.json
  connectors/aws/aws-s3/pom.xml
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/S3ConnectorFunction.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/core/S3Executor.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/request/DeleteObject.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/request/DownloadObject.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/request/S3Action.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/request/S3Request.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/request/UploadObject.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/response/DeleteResponse.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/response/DownloadResponse.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/response/Element.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/model/response/UploadResponse.java
  connectors/aws/aws-s3/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/aws/aws-s3/src/main/resources/icon.svg
  connectors/aws/aws-s3/src/test/java/io/camunda/connector/aws/s3/BaseTest.java
  connectors/aws/aws-s3/src/test/java/io/camunda/connector/aws/s3/S3ConnectorFunctionTest.java
  connectors/aws/aws-s3/src/test/java/io/camunda/connector/aws/s3/core/S3ExecutorTest.java
  connectors/aws/aws-s3/src/test/resources/actions/deleteActionsExample.json
  connectors/aws/aws-s3/src/test/resources/actions/downloadActionsExample.json
  connectors/aws/aws-s3/src/test/resources/actions/uploadActionsExample.json
  connectors/aws/pom.xml
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
Labels: component:qa, deploy-preview, qa:required
