Repository camunda/connectors, pull requests merged in 2024-11, with the labels that each got.

#3570 fix(generator): boolean conditions in template generator annotations
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java
Labels: no milestone

#3548 chore(tests): Random port for Wiremock
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: no milestone

#3575 fix(inbound): exclude output mappings from deduplication
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/Keywords.java
Labels: deploy-preview, backport release/8.6

#3578 feat(idp-extraction-connector): added compatibility with llms lacking system message support
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/BedrockCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/LlmModel.java
Labels: no milestone

#3642 feat(idp-extraction-connector): update prompt for llama llm
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/LlmModel.java
Labels: no milestone

#3657 fix(email-connector): removing cancellation event when a exception is raised during email consumption
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
Labels: backport release/8.6

#3569 feat(mail-connector): Adding Dropdown for Outbound Connector to switch content type between plain text and html
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/BaseEmailTest.java
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/InboundEmailTest.java
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/OutboundEmailTests.java
  connectors/email/element-templates/email-outbound-connector.json
  connectors/email/element-templates/hybrid/email-outbound-connector-hybrid.json
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/ContentType.java
  connectors/email/src/main/java/io/camunda/connector/email/outbound/protocols/actions/SmtpSendEmail.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java
Labels: deploy-preview, qa:required
