Repository camunda/connectors, pull requests merged in 2024-03, with the labels that each got.

#2038 fix(importer): prevent OOM by filtering out older process versions early on
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
  connectors-e2e-test/connectors-e2e-test-automation-anywhere/src/test/java/io/camunda/connector/e2e/BaseAutomationAnywhereTest.java
  connectors-e2e-test/connectors-e2e-test-aws/connectors-e2e-test-aws-base/src/test/java/io/camunda/connector/e2e/BaseAwsTest.java
  connectors-e2e-test/connectors-e2e-test-easy-post/src/test/java/io/camunda/connector/e2e/BaseEasyPostTest.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
  connectors-e2e-test/connectors-e2e-test-kafka/src/test/java/io/camunda/connector/e2e/BaseKafkaTest.java
  connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/BaseRabbitMqTest.java
  connectors-e2e-test/connectors-e2e-test-soap/src/test/java/io/camunda/connector/e2e/soap/SoapConnectorBaseTest.java
Labels: backport release/8.3, backport release/8.4

#2093 chore(workflow): update release run name
  .github/workflows/RELEASE.yaml
Labels: backport release/8.3, backport release/8.4

#2091 fix(kafka): fix deserialization of escaped characters
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Labels: backport release/8.3, backport release/8.4

#2128 fix(generator): reorder inbound correlation properties
  connectors/webhook/element-templates/webhook-connector-boundary.json
  connectors/webhook/element-templates/webhook-connector-intermediate.json
  connectors/webhook/element-templates/webhook-connector-start-message.json
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/InboundClassBasedTemplateGeneratorTest.java
Labels: kind:bug, component:template-generator, version:8.5.0-alpha2

#2164 fix: revert to v4 EasyPost template
  connectors/easy-post/element-templates/easy-post-connector.json
Labels: backport release/8.5

#2187 fix(sqs): increase polling wait time default to reduce cpu usage
  connectors/aws/aws-sqs/element-templates/aws-sqs-boundary-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-inbound-intermediate-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-start-event-connector.json
  connectors/aws/aws-sqs/element-templates/aws-sqs-start-message.json
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/model/SqsInboundQueueProperties.java
Labels: scope:sqs

#2217 fix(feel): fixed timestamp serialization
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
  connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java
  connector-sdk/feel-wrapper/src/test/java/io/camunda/connector/feel/FeelEngineWrapperExpressionEvaluationTest.java
Labels: backport release/8.3

#2240 fix(kafka): fix kafka deserialization
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaPropertyTransformer.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Labels: backport release/8.3, backport release/8.4
