Repository camunda/connectors, pull requests merged in 2024-02, with the labels that each got.

#1883 fix(inbound): fix saving already processed process definition keys
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java
Labels: backport release/8.3, backport release/8.4

#1935 build(release): add a step to update version in the release branch
  .github/workflows/RELEASE.yaml
Labels: ci/cd, backport release/8.3, backport release/8.4, backport release/8.5

#1880 feat(actuator): add readiness indicator for Zeebe & Operate connections
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/default-bundle/src/test/resources/application.properties
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ConnectorsObservabilityAutoConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OperateHealthIndicator.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ZeebeHealthIndicator.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/META-INF/spring.factories
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: backport release/8.3, backport release/8.4

#1937 chore: support Java 17 for Connector SDK
  connector-sdk/core/pom.xml
  connector-sdk/feel-wrapper/pom.xml
  connector-sdk/jackson-datatype-feel/pom.xml
  connector-sdk/pom.xml
  connector-sdk/test/pom.xml
  connector-sdk/validation/pom.xml
  parent/pom.xml
  pom.xml
Labels: scope:sdk, backport release/8.4

#2021 fix(importer): handle missing required properties as invalid connector definition exception
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionInspector.java
Labels: backport release/8.3, backport release/8.4

#1983 chore(spring-zeebe): Upgrade to spring zeebe 8.4.2-rc1
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
  parent/pom.xml
Labels: backport release/8.4

#2029 Fix CWE 770 and CWE 835
  connectors-e2e-test/connectors-e2e-test-kafka/pom.xml
  connectors/soap/src/test/java/io/camunda/connectors/soap/xml/XmlToJsonMapperTest.java
  connectors/webhook/pom.xml
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4

#2050 http connector: use tcp socket timeout
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/components/HttpTransportComponentSupplier.java
Labels: backport release/8.4
