Repository camunda/connectors, pull requests merged in 2024-06, with the labels that each got.

#2708 fix(docs): Fix wrong documentation link
  connectors/aws/aws-sagemaker/element-templates/aws-sagemaker-outbound-connector.json
  connectors/aws/aws-sagemaker/element-templates/hybrid/aws-sagemaker-outbound-connector-hybrid.json
  connectors/aws/aws-sagemaker/src/main/java/io/camunda/connector/sagemaker/SagemakerConnectorFunction.java
Labels: backport release/8.6

#2728 ci(integration): use new args for re-usable Helm integration test
  .github/workflows/INTEGRATION_TEST.yml
  .github/workflows/helm-git-refs.json
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#2700 fix(deps): Bump spring-zeebe to 8.5.4
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/ObjectMapperSerializationTest.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqMessageProperties.java
  parent/pom.xml
Labels: backport release/8.5

#2747 deps(spring-zeebe): Bump spring zeebe to 8.5.5
  parent/pom.xml
Labels: backport release/8.5

#2771 chore(readme): remove wrong env var hyphen usage
  connector-runtime/README.md
  secret-providers/gcp-secret-provider/README.md
Labels: kind:documentation

#2779 fix(helm): Fix Helm integration tests
  .github/workflows/helm-git-refs.json
Labels: backport release/8.5, backport release/8.6

#2775 fix(webhook): specify permitted auth subclasses explicitly to stabilize template generation
  connectors/webhook/src/main/java/io/camunda/connector/inbound/model/WebhookAuthorization.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5

#2787 fix(webhook): support failure handling strategy
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/CorrelationResult.java
Labels: backport release/8.6

#2793 fix(rest): Fix NPE with readTimeoutInSeconds + Duplicate headers
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.6

#2790 feature 653 update version for slack outbound connector fromn 3 to 4
  connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
  connectors/slack/element-templates/slack-outbound-connector.json
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
Labels: backport release/8.6

#2799 fix(rest): Fix Timeout default value and OAuth empty scopes issues
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/auth/OAuthAuthentication.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/authentication/OAuthServiceTest.java
  connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java
  connectors/http/rest/src/test/resources/requests/success-test-cases-oauth.json
Labels: backport release/8.6

#2801 Fix read timeout with cloud function
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
Labels: backport release/8.6

#2797 chore(preview-env): add dockerhub pull secret
  .ci/preview-environments/charts/c8sm/templates/secrets.yml
  .ci/preview-environments/charts/c8sm/values.yaml
Labels: deploy-preview
