Repository camunda/connectors, pull requests merged in 2024-04, with the labels that each got.

#2310 feat(generator): support inbound deduplication; boolean props; enhanced conditions
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElement.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
  connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-boundary.json
  connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-intermediate.json
  connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-message-start.json
  connectors/rabbitmq/element-templates/rabbitmq-inbound-connector-start-event.json
  connectors/rabbitmq/pom.xml
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java
  element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/ConGen.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/api/GeneratorConfiguration.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BooleanProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/CommonProperties.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/DropdownProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/HiddenProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/Property.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyBuilder.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyCondition.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyGroup.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/StringProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/TextProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedTemplateGenerator.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/ElementTemplate.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/annotation/TemplateProperty.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/processor/TemplatePropertyFieldProcessor.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/ConfigurationUtil.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplatePropertiesUtil.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/ElementTemplateSerializationTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/InboundClassBasedTemplateGeneratorTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorFunction.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorInput.java
  element-template-generator/core/src/test/resources/test-element-template.json
  element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ConnectorConfig.java
  element-template-generator/maven-plugin/src/main/java/io/camunda/connector/generator/ElementTemplateGeneratorMojo.java
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
  element-template-generator/postman-collections-parser/src/main/java/io/camunda/connector/generator/postman/PostmanCollectionOutboundTemplateGenerator.java
  element-template-generator/postman-collections-parser/src/test/java/io/camunda/connector/generator/postman/PostmanCollectionsGeneratorDryRunExampleTest.java
Labels: component:template-generator

#2317 chore(deps): update org.bouncycastle dependency to v1.78
  connectors/sendgrid/pom.xml
  connectors/soap/pom.xml
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4, backport release/8.5

#2351 chore: migrate to spring zeebe 8.5.1
  bundle/default-bundle/src/test/resources/application.properties
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/PublishMessageCommandDummy.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java
  parent/pom.xml
Labels: backport release/8.5, backport release/8.6
