Repository camunda/connectors, pull requests merged in 2024-10, with the labels that each got.

#3408 other(cve): Fix CVE-2024-7254
  .gitignore
  bundle/camunda-saas-bundle/pom.xml
  connectors/pom.xml
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#3415 fix(sqs): fail fast when queue does not exist
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6

#3422 fix(sqs): fail fast when queue does not exist (#3415)
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Labels: no milestone

#3420 fix(sqs): fail fast when queue does not exist (#3415)
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Labels: no milestone

#3421 fix(sqs): fail fast when queue does not exist (#3415)
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsExecutable.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
Labels: no milestone

#3416 chore(element-templates): Replace deprecated Zeebe binding by the new version
  connectors/asana/element-templates/asana-connector.json
  connectors/aws/aws-base/README.md
  connectors/blue-prism/element-templates/blue-prism-connector.json
  connectors/github/element-templates/github-connector.json
  connectors/gitlab/element-templates/gitlab-connector.json
  connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
  connectors/hugging-face/element-templates/hugging-face-connector.json
  connectors/openai/element-templates/openai-connector.json
  connectors/operate/element-templates/operate-connector.json
  connectors/salesforce/element-templates/salesforce-connector.json
Labels: backport release/8.5, backport release/8.6

#3456 ci(backport-pr): prevent loop on backport fail
  .github/workflows/BACKPORT_PR.yml
Labels: backport release/8.6, no milestone

#3460 feat(proxy): Proxy exception list for outbound http connectors
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/ProxyConfiguration.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/resources/squid.conf
Labels: backport release/8.6

#3468 ci(helm-git-refs): use new refs after 8.6 release
  .github/workflows/helm-git-refs.json
Labels: backport release/8.6, no milestone

#3473 ci(create-release-branch): update PR details
  .github/workflows/CREATE_RELEASE_BRANCH.yml
Labels: no milestone

#3474 fix(rest): Add retries and synchronize OAuth credentials init for the Cloud Function
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionCredentialsCache.java
Labels: backport release/8.6

#3476 chore(preview-environment): Update Chart.yaml
  .ci/preview-environments/charts/c8sm/Chart.yaml
Labels: no milestone

#3482 feat(idp extraction connector): implement new idp extraction outbound connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors-e2e-test/connectors-e2e-test-mail/pom.xml
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/pom.xml
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/BedrockCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/BaseRequest.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ConverseData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequest.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionResult.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TaxonomyItem.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextExtractionEngineType.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTask.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/BedrockRuntimeClientSupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/S3ClientSupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/TextractClientSupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/AwsS3Util.java
  connectors/idp-extraction/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/idp-extraction/src/main/resources/icon.svg
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/BedrockCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/BedrockRuntimeClientSupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/S3ClientSupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/TextractClientSupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/util/ExtractionTestUtils.java
  connectors/idp-extraction/src/test/resources/icon.svg
  connectors/pom.xml
  parent/pom.xml
Labels: no milestone

#3499 fix(preview-environments): Adapt to C8 Helm chart v11
  .ci/preview-environments/charts/c8sm/templates/ingress.yml
  .ci/preview-environments/charts/c8sm/templates/service.yml
  .ci/preview-environments/charts/c8sm/values.yaml
Labels: deploy-preview, no milestone

#3510 chore(logs): Add an endpoint to publish inbound logs
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundConnectorRestController.java
Labels: backport release/8.6, no milestone

#3518 fix(webhook): Fix webhook and possible http client nullpointer exception
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-runtime/spring-boot-starter-camunda-connectors/pom.xml
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
Labels: backport release/8.6

#3527 chore(loggers): Enable log level actuator endpoint
  bundle/camunda-saas-bundle/src/main/resources/application.properties
Labels: backport release/8.6

#3506 fix(email-inbound-connector): implement a reconnect and reopen mechanism
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/BaseEmailTest.java
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/InboundEmailTest.java
  connectors-e2e-test/connectors-e2e-test-mail/src/test/java/io/camunda/connector/e2e/OutboundEmailTests.java
  connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-inbound-connector-intermediate_all_delete.bpmn
  connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-inbound-connector-intermediate_all_move.bpmn
  connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-inbound-connector-intermediate_unseen_delete.bpmn
  connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-inbound-connector-intermediate_unseen_move.bpmn
  connectors-e2e-test/connectors-e2e-test-mail/src/test/resources/email-inbound-connector-intermediate_unseen_read.bpmn
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/JakartaEmailListener.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/utils/JakartaUtils.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/JakartaExecutorTest.java
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
Labels: deploy-preview, backport release/8.6
