Repository camunda/connectors, pull requests merged in 2025-08, with the labels that each got.

#5172 other(logging): log the exception when an error occurs
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
Labels: no milestone

#5181 other(release): Set a custom Maven deployment name
  pom.xml
Labels: no milestone, backport release/8.8

#5188 docs(links): fix documentation links
  connectors/http/rest/README.md
  connectors/microsoft/azure-blobstorage/element-templates/azure-blobstorage-outbound-connector.json
  connectors/microsoft/azure-blobstorage/element-templates/hybrid/azure-blobstorage-outbound-connector-hybrid.json
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/BlobStorageConnectorFunction.java
  connectors/operate/element-templates/operate-connector.json
Labels: no milestone

#5185 chore(deps): block further spring-zeebe version bumps for 8.5
  renovate.json
Labels: no milestone

#5218 fix(idp-extraction-connector): backporting issue 5211 to 8.7
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTextDetectionTask.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
Labels: no milestone

#5199 fix(webhook): add a queue for duplicate webhooks so that they be reactived later
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookExecutables.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistryLogTest.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistryTest.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/webhook/WebhookExecutablesTest.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/webhook/WebhookTestsBase.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/BaseWebhookTest.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerPlainJavaTests.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestExceptionZeebeTest.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTest.java
Labels: backport release/8.6, backport release/8.7

#5205 refactor(agentic-ai): Align `fromAi()` parameter extraction with core engine logic
  connectors/agentic-ai/pom.xml
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/CamundaClientProcessDefinitionAdHocToolElementsResolver.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/AdHocToolElementParameterExtractor.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/AdHocToolElementParameterExtractorImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/FeelExpressionParameterExtractor.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/FeelExpressionParameterExtractorImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/FeelFunctionInvocationExtractor.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/adhoctoolsschema/schema/AdHocToolSchemaGeneratorImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/AdHocToolsSchemaFunctionIntegrationTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/AdHocToolElementParameterExtractorTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/processdefinition/feel/FeelExpressionParameterExtractorTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/schema/AdHocToolSchemaGeneratorTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfigurationTest.java
  parent/pom.xml
Labels: agentic-ai

#5235 fix(deps): renovate config fix
  renovate.json
Labels: no milestone

#5248 fix(agentic-ai): fix NPE when agent context flag is null
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/JobWorkerAgentRequestHandler.java
Labels: agentic-ai

#5260 test(spring): failing tests after refactoring
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTest.java
Labels: no milestone

#5264 test(runtime): fix search query client test
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java
Labels: no milestone

#5265 fix(runtime): move Value to the configuration
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java
Labels: no milestone

#5281 chore(client): Fix return type of error
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
Labels: no milestone

#5302 fix(ci): update regexp for pull_request name check
  .github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml
Labels: no milestone

#5314 fix(runtime): add message to health status update activity logs
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/ActivityLogTag.java
  connectors/http/polling/src/main/java/io/camunda/connector/http/polling/HttpPollingConnector.java
Labels: backport release/8.8
