Repository camunda/connectors, pull requests merged in 2025-01, with the labels that each got.

#3829 chore(ci): Fix Helm chart version
  .github/workflows/helm-git-refs.json
Labels: no milestone

#3753 feat(box-connector): Box Connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/box/LICENSE.txt
  connectors/box/element-templates/box-outbound-connector.json
  connectors/box/element-templates/hybrid/box-outbound-connector-hybrid.json
  connectors/box/pom.xml
  connectors/box/src/main/java/io/camunda/connector/box/BoxFunction.java
  connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java
  connectors/box/src/main/java/io/camunda/connector/box/BoxUtil.java
  connectors/box/src/main/java/io/camunda/connector/box/model/BoxPath.java
  connectors/box/src/main/java/io/camunda/connector/box/model/BoxRequest.java
  connectors/box/src/main/java/io/camunda/connector/box/model/BoxResult.java
  connectors/box/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/box/src/main/resources/icon.svg
  connectors/box/src/test/java/io/camunda/connector/BoxPathTests.java
  connectors/pom.xml
  parent/pom.xml
Labels: deploy-preview

#3827 feat(element-template-generator): allow send tasks using connectors
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/BpmnType.java
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/util/TemplateGenerationContextUtil.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/dsl/ElementTypeSupportTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/OutboundClassBasedTemplateGeneratorTest.java
  element-template-generator/core/src/test/java/io/camunda/connector/generator/java/example/outbound/MyConnectorFunction.java
Labels: backport release/8.6, no milestone

#3836 chore(ci): fixed no disk space in github action
  .github/workflows/RELEASE.yaml
Labels: no milestone, backport release/8.7

#3837 fix(rest): fix sending null params in a body map
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/utils/DocumentHelper.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java
Labels: no milestone, backport release/8.7

#3835 feat(idp-extraction-connector): update the idp connector to accept documents
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/AwsS3Util.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/BedrockCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/util/ExtractionTestUtils.java
  connectors/idp-extraction/src/test/resources/sample-invoice.pdf
Labels: no milestone

#3845 feat(authentication-webhook): change way to retrieve algorithm, more …
  connectors/webhook/src/main/java/io/camunda/connector/inbound/authorization/JWTAuthHandler.java
  connectors/webhook/src/test/java/io/camunda/connector/inbound/authorization/JWTAuthHandlerTest.java
Labels: backport release/8.6

#3854 fix(config): apply new configuration in saas yaml file
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/TestSpringContextStartup.java
Labels: backport release/8.7

#3851 feat(jackson): enable 'accept single value as array' globally
  connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
  connector-sdk/core/src/test/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplierTest.java
Labels: no milestone

#3852 others(QA): Enfore qa when feat pr is created
  .github/workflows/ENFORCE_QA_APPROVAL.yml
Labels: deploy-preview

#3859 feat(rest-connector): Add flag to get multiple set cookie headers as list
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/exception/ConnectorExceptionMapper.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonResult.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandlerTest.java
  connectors/http/rest/element-templates/http-json-connector.json
  connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
  connectors/http/rest/src/main/java/io/camunda/connector/http/rest/HttpJsonFunction.java
Labels: backport release/8.6

#3857 fix(config): update saas clusterid reference
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConfiguration.java
Labels: no milestone

#3828 feat(textract doc handle): add documentation handling for textract
  connectors/aws/aws-textract/element-templates/aws-textract-outbound-connector.json
  connectors/aws/aws-textract/element-templates/hybrid/aws-textract-outbound-connector-hybrid.json
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/TextractConnectorFunction.java
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/caller/SyncTextractCaller.java
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/DocumentLocationType.java
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/TextractRequestData.java
  connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/AsyncTextractCallerTest.java
  connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/SyncTextractCallerTest.java
  connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/caller/TextractCallerTest.java
  connectors/aws/aws-textract/src/test/java/io/camunda/connector/textract/util/TextractTestUtils.java
Labels: deploy-preview

#3873 fix(kafka): fix Kafka connector deactivate method
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java
Labels: support, backport release/8.6
