Repository camunda/connectors, pull requests merged in 2025-07, with the labels that each got.

#5001 refactor(agentic-ai): remove experimental from MCP client connector names
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpClientFunction.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpRemoteClientFunction.java
Labels: agentic-ai

#4940 other(util): introduce pre-commit
  .pre-commit-config.yaml
  .tool-versions
  README.md
  bundle/README.md
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultInboundConnectorFactory.java
Labels: no milestone

#5004 fix(agentic-ai): properly provide Spring configuration metadata for the agentic AI module
  connectors/agentic-ai/pom.xml
  connectors/agentic-ai/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: no milestone, agentic-ai

#4977 fix(google-maps): Fix address line null in validate address
  connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
Labels: deploy-preview, backport release/8.4, backport release/8.5, backport release/8.6, qa:required, backport release/8.7

#5014 ci(renovate): update renovate.json
  renovate.json
Labels: no milestone

#5018 other(security): fix potential security breach in our GHA
  .github/workflows/PULL_REQUEST_NAME_CHECK_ON_PR.yml
Labels: no milestone

#5021 fix(google-maps): Fix address line null in validate address (#4977)
  connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
Labels: no milestone

#5022 fix(google-maps): Fix address line null in validate address (#4977)
  connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
Labels: no milestone

#5035 feat(agentic-ai): custom storage implementation support
  connectors/agentic-ai/CHANGELOG.md
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/AgentRequestHandlerImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStore.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStoreFactoryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStoreRegistry.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStoreRegistryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/document/CamundaDocumentConversationStore.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/memory/conversation/inprocess/InProcessConversationStore.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/MemoryStorageConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/agent/AgentRequestHandlerTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStoreFactoryTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/memory/conversation/ConversationStoreRegistryTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/memory/conversation/document/CamundaDocumentConversationStoreTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/memory/conversation/inprocess/InProcessConversationStoreTest.java
Labels: agentic-ai

#5050 chore(agentic-ai): remove deprecated alpha4 compatibility template
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector-8.8.0-alpha4.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-8.8.0-alpha4-hybrid.json
Labels: agentic-ai

#5033 fix(docs-link): Adjust link
  connectors/operate/element-templates/operate-connector.json
  connectors/operate/element-templates/versioned/operate-connector-4.json
Labels: no milestone

#5082 docs(agentic-ai): Update AI Agent connector template agent context helper text
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
Labels: agentic-ai

#4875 feat(azure-blobstorage): Add azure blobstorage connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/microsoft/azure-blobstorage/element-templates/azure-blobstorage-outbound-connector.json
  connectors/microsoft/azure-blobstorage/element-templates/hybrid/azure-blobstorage-outbound-connector-hybrid.json
  connectors/microsoft/azure-blobstorage/pom.xml
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/BlobStorageConnectorFunction.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/core/BlobStorageExecutor.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/request/Authentication.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/request/BlobStorageOperation.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/request/BlobStorageRequest.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/request/DownloadBlob.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/request/UploadBlob.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/response/DownloadResponse.java
  connectors/microsoft/azure-blobstorage/src/main/java/io/camunda/connector/azure/blobstorage/model/response/UploadResponse.java
  connectors/microsoft/azure-blobstorage/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/microsoft/azure-blobstorage/src/main/resources/icon.svg
  connectors/pom.xml
Labels: deploy-preview, qa:required

#5017 feat(gcs): Add google cloud storage connector
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors/google/google-gcs/element-templates/google-cloud-storage-outbound-connector.json
  connectors/google/google-gcs/element-templates/hybrid/hybrid-google-cloud-storage-outbound-connector-hybrid.json
  connectors/google/google-gcs/pom.xml
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/ObjectStorageConnectorFunction.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/core/ObjectStorageExecutor.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/request/Authentication.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/request/DownloadObject.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/request/ObjectStorageOperation.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/request/ObjectStorageRequest.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/request/UploadObject.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/response/DownloadResponse.java
  connectors/google/google-gcs/src/main/java/io/camunda/connector/google/gcs/model/response/UploadResponse.java
  connectors/google/google-gcs/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/google/google-gcs/src/main/resources/icon.svg
  connectors/google/pom.xml
Labels: deploy-preview, qa:required

#5077 fix(idp-extraction-connector): added integration for azure
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/pom.xml
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/AzureAiFoundryCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/AzureDocumentIntelligenceCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/AzureProvider.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/ProviderConfig.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/azure/AiFoundryConfig.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/azure/DocumentIntelligenceConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/UnstructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/AzureAiFoundrySupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/StringUtil.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/AzureAiFoundryCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/AzureDocumentIntelligenceCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/UnstructuredServiceTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/AzureAiFoundrySupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/utils/StringUtilTest.java
Labels: no milestone

#5083 feat(agentic-ai): add support for Azure OpenAI models
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/pom.xml
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java
Labels: agentic-ai

#5089 feat(agentic-ai): support Google Vertex AI models
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/pom.xml
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactory.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/AgentRequest.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/AnthropicProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/AzureOpenAiProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/BedrockProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/GoogleVertexAiProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/OpenAiProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/ProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/model/tool/ToolCall.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/util/BpmnUtils.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/util/ConnectorUtils.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/util/PromptUtils.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/Langchain4JAiFrameworkAdapterTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfigurationTest.java
Labels: agentic-ai

#5103 chore(tests): Fix failing main
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java
Labels: no milestone

#5048 feat(inbound): Fetch only the latest process definitions
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/DataImportConfiguration.java
  bundle/default-bundle/src/test/resources/data-import/QA Review Process.bpmn
  connector-runtime/connector-runtime-spring/pom.xml
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientImpl.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/EmptyConfiguration.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/SearchQueryClientTest.java
Labels: deploy-preview, qa:required

#5122 fix(open-api): all generated templates will now validate the result against the JSON schema
  element-template-generator/congen-cli/pom.xml
  element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/ReturnCodes.java
  element-template-generator/congen-cli/src/main/java/io/camunda/connector/generator/cli/command/Generate.java
Labels: backport release/8.7

#5147 test(agentic-ai): simplify e2e test setup with newly added CPT methods
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/AiAgentTestFixtures.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/BaseAiAgentTest.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentElementTemplateRegressionTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentFeedbackLoopTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentLimitsTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMcpIntegrationTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java
Labels: no milestone

#5049 feat(gdrive): Add support for shared drives
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveClient.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveService.java
  connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveClientTest.java
  connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveServiceTest.java
Labels: deploy-preview, backport release/8.5, backport release/8.6, qa:required, backport release/8.7

#5151 refactor(connector-runtime): revert refactor outbound connector registration (#5124)
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorFactory.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultInboundConnectorFactory.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorFactory.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/DefaultOutboundConnectorFactory.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/OutboundConnectorDiscoveryTest.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessor.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessorTest.java
Labels: no milestone

#5156 fix(DummyCommand): Implement terminateAfterElement
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java
Labels: no milestone, backport release/8.8

#5159 other(javadoc): Fix javadoc link
  connector-sdk/core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorProvider.java
Labels: no milestone, backport release/8.8

#5167 refactor(agentic-ai): Move implementation specific tool resolution to outbound connector execution context
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/AiAgentFunction.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/agent/AgentInitializerImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentExecutionContext.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/OutboundConnectorAgentExecutionContext.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/autoconfigure/AgenticAiConnectorsAutoConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/agent/AgentInitializerTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/OutboundConnectorAgentExecutionContextTest.java
Labels: agentic-ai

#5170 chore(config): Explicitly disable automatic job completion. Add job t…
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
Labels: backport release/8.6, no milestone, backport release/8.7

#5173 chore(github): Automatically add bugs to the quality board
  .github/workflows/ADD_TO_PROJECT.yml
Labels: no milestone
