Repository camunda/connectors, pull requests merged in 2025-03, with the labels that each got.

#4139 chore(element-tempaltes): Add github action for bumping element templ…
  .github/workflows/BUMP_ELEMENT_TEMPLATE_DOCS_LINKS.yml
  .github/workflows/scripts/collect_all_element_template_docs_links.sh
Labels: no milestone

#3862 fix(ci): configure camunda-nexus mirror in correctly
  .github/workflows/BUILD_FEATURE_BRANCH.yaml
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
  .github/workflows/RELEASE.yaml
  .github/workflows/TEST_FEATURE_BRANCH.yml
  connectors/soap/pom.xml
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone, backport release/8.7

#4178 fix(ci): typo in a workflow
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
Labels: no milestone

#4170 fix(deps): operate client 8.6.5
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSOperateClientFactory.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretApiClient.java
  parent/pom.xml
Labels: no milestone

#4180 fix(ci): nexus mirror
  .github/workflows/BUILD_FEATURE_BRANCH.yaml
  .github/workflows/DEPLOY_8.7_SNAPSHOTS.yaml
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
  .github/workflows/RELEASE.yaml
  .github/workflows/TEST_FEATURE_BRANCH.yml
  parent/pom.xml
Labels: no milestone

#4147 feat(idp-extraction-connector): idp connector should return response as key/value pair of extracted fields
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionResult.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java
Labels: no milestone

#4181 fix(ci): nexus mirror
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
  .github/workflows/RELEASE.yaml
  .github/workflows/TEST_FEATURE_BRANCH.yml
  parent/pom.xml
Labels: no milestone

#4184 fix(ci): nexus mirror
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
  .github/workflows/RELEASE.yaml
  .github/workflows/TEST_FEATURE_BRANCH.yml
  parent/pom.xml
Labels: no milestone

#4183 fix(ci): nexus mirror
  .github/workflows/DEPLOY_SNAPSHOTS.yaml
  .github/workflows/RELEASE.yaml
  .github/workflows/TEST_FEATURE_BRANCH.yml
  parent/pom.xml
Labels: no milestone

#4191 fix(security): Disallow include in pebble engine
  element-template-generator/core/src/main/java/io/camunda/connector/generator/java/ClassBasedDocsGenerator.java
Labels: backport release/8.6, backport release/8.7

#4203 chore(cors): fix cors config for /inbound-instances subpaths
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java
  bundle/default-bundle/src/test/resources/application-local.properties
  renovate.json
Labels: backport release/8.7

#4210 chore(license): create LICENSE.txt file
  LICENSE.txt
Labels: no milestone

#4207 chore(cors): fix cors config for /inbound-instances subpaths
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
  bundle/camunda-saas-bundle/src/main/resources/application.properties
Labels: no milestone

#4163 chore(ci): update preview environment deployment with new troubleshooting capabilities
  .github/workflows/PREVIEW-ENV-DEPLOY.yml
Labels: no milestone

#4215 chore(cors): fix authenticated path after API changes
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
Labels: no milestone, backport release/8.7

#4168 chore(element-templates): Add ci check for element template next links
  .github/workflows/TEST_FEATURE_BRANCH.yml
  connectors/aws/aws-comprehend/element-templates/aws-comprehend-outbound-connector.json
  connectors/aws/aws-comprehend/element-templates/hybrid/aws-comprehend-outbound-connector-hybrid.json
  connectors/aws/aws-comprehend/src/main/java/io/camunda/connector/comprehend/ComprehendConnectorFunction.java
  connectors/aws/aws-sagemaker/element-templates/aws-sagemaker-outbound-connector.json
  connectors/aws/aws-sagemaker/element-templates/hybrid/aws-sagemaker-outbound-connector-hybrid.json
  connectors/aws/aws-sagemaker/src/main/java/io/camunda/connector/sagemaker/SagemakerConnectorFunction.java
  connectors/aws/aws-textract/element-templates/aws-textract-outbound-connector.json
  connectors/aws/aws-textract/element-templates/hybrid/aws-textract-outbound-connector-hybrid.json
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/TextractConnectorFunction.java
  connectors/aws/aws-textract/src/main/java/io/camunda/connector/textract/model/TextractRequestData.java
  connectors/jdbc/element-templates/hybrid/jdbc-outbound-connector-hybrid.json
  connectors/jdbc/element-templates/jdbc-outbound-connector.json
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/JdbcRequestData.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/connection/DetailedConnection.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/connection/UriConnection.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/outbound/JdbcFunction.java
  element-template-generator/postman-collections-parser/src/test/resources/operate-api-saas-bearer.json
Labels: no milestone

#4223 chore(api): increase allowed headers size to 1MB
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/default-bundle/src/main/resources/application.properties
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
Labels: no milestone, backport release/8.7

#4262 chore(api): increase allowed headers size to 1MB (#4223)
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/default-bundle/src/main/resources/application.properties
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
Labels: no milestone

#4267 fix(deps): bump dependencies to fix CVEs
  parent/pom.xml
Labels: backport release/8.3, backport release/8.4, no milestone

#4264 chore(deps): enable minor version upgrades on release branches
  renovate.json
Labels: no milestone

#4295 other(tests): fix proxy tests, clear properties properly
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
Labels: no milestone

#4270 fix(deps): bump dependencies to fix CVEs (8.3)
  parent/pom.xml
Labels: no milestone

#4202 fix(rest-connector): Return always an array for set cookie headers
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/HttpCommonResultResponseHandlerTest.java
  connectors/http/rest/element-templates/http-json-connector.json
  connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
Labels: backport release/8.6, backport release/8.7

#4306 chore: move to zeebe 8.6
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/CreateCommandDummy.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/testutil/command/PublishMessageCommandDummy.java
  connector-runtime/spring-boot-starter-camunda-connectors/pom.xml
  parent/pom.xml
Labels: no milestone

#4356 chore(idp-extraction-connector): rename results map
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/VertexCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionResult.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/VertexCallerTest.java
Labels: no milestone, backport release/8.7

#4369 fix(renovate.json): Fix SNAPSHOT filter
  renovate.json
Labels: no milestone

#4381 fix(build): upgrade packages in docker images
  bundle/camunda-saas-bundle/Dockerfile
  bundle/default-bundle/Dockerfile
  connector-runtime/connector-runtime-application/Dockerfile
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone, backport release/8.7

#4376 feat(ms-teams): Add document handling for sending message to channel
  connectors/microsoft-teams/element-templates/hybrid/microsoft-teams-outbound-connector-hybrid.json
  connectors/microsoft-teams/element-templates/microsoft-teams-outbound-connector.json
  connectors/microsoft-teams/src/main/java/io/camunda/connector/MSTeamsFunction.java
  connectors/microsoft-teams/src/main/java/io/camunda/connector/model/request/data/SendMessageToChannel.java
  connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/channel/DocumentHandler.java
  connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/channel/SendMessageToChannelOperation.java
  connectors/microsoft-teams/src/test/java/io/camunda/connector/model/request/channel/SendMessageToChannelTest.java
Labels: deploy-preview, qa:required, backport release/8.7

#4162 feat(element-template-generator): Improve openAPI handling
  element-template-generator/core/src/main/java/io/camunda/connector/generator/dsl/PropertyBinding.java
  element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpAuthentication.java
  element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
  element-template-generator/http-dsl/src/test/java/io/camunda/connector/generator/dsl/http/HttpOutboundElementTemplateBuilderTest.java
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/BodyUtil.java
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java
  element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/PublicSpecsTest.java
  element-template-generator/openapi-parser/src/test/resources/publicSpecs/paycom.yaml
  element-template-generator/openapi-parser/src/test/resources/publicSpecs/paypalcheckout.yaml
  element-template-generator/openapi-parser/src/test/resources/publicSpecs/peachpay.yaml
  element-template-generator/openapi-parser/src/test/resources/publicSpecs/stripe.yaml
Labels: deploy-preview, qa:required, backport release/8.7

#4320 refactor(rest): refactor the proxy support for the REST Connector
  .ci/preview-environments/charts/c8sm/values.yaml
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/HttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestAuthenticationBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyAwareHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyHandler.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/proxy/ProxyRoutePlanner.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ApacheRequestFactoryTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/proxy/ProxyRoutePlannerTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
  connectors/http/rest/src/test/java/io/camunda/connector/http/rest/HttpServiceTest.java
Labels: deploy-preview, backport release/8.6, qa:required, backport release/8.7

#4380 fix(rest): fix document upload in SaaS, using multipart requests
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/DocumentAwareMultipartEntityBuilder.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionFilePart.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java
Labels: qa:required, backport release/8.7

#4393 feat(office-365): send documents via email
  connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json
Labels: deploy-preview, qa:required, backport release/8.7

#4388 refactor(deduplicationId): change the executableIds from UUID to a hashed deduplicationId for stability across runtimes
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/ExecutableId.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElement.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/details/InboundConnectorDetails.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/InboundConnectorElementTest.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/ActiveInboundConnectorResponse.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/controller/InboundInstancesRestController.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/ActiveExecutableResponse.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableEvent.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryImpl.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/executable/InboundExecutableRegistryTest.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundEndpointTest.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundInstancesRestControllerTest.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonRequest.java
  connectors/http/rest/element-templates/http-json-connector.json
  connectors/http/rest/element-templates/hybrid/http-json-connector-hybrid.json
Labels: qa:required, backport release/8.7

#4378 feature(inbound-connector): messageId can be defined within the inbound connector, this will be overriden if a customer specifies one
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/DefaultProcessInstanceContext.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandler.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/inbound/correlation/InboundCorrelationHandlerTest.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/CorrelationRequest.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java
  connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
  connectors/aws/aws-sqs/src/main/java/io/camunda/connector/inbound/SqsQueueConsumer.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsExecutableTest.java
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsQueueConsumerTest.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
  connectors/email/src/test/java/io/camunda/connector/email/client/jakarta/PollingManagerTest.java
  connectors/email/src/test/java/io/camunda/connector/email/integration/InboundEmailTest.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumerTest.java
Labels: backport release/8.7

#4409 fix(metric): proc def metric has incorrect name
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/metrics/ConnectorMetrics.java
Labels: backport release/8.6, backport release/8.7

#4403 refactor(office-365): use an intrinsic function for sending base64 documents
  connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json
Labels: backport release/8.7

#4413 chore(renovate.json): Use glob matching
  renovate.json
Labels: no milestone

#4415 chore(renovate): Update renovate.json
  renovate.json
Labels: no milestone

#4420 fix(test): sqs test potentially flaky
  connectors/aws/aws-sqs/src/test/java/io/camunda/connector/inbound/SqsQueueConsumerTest.java
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone, backport release/8.7

#4422 chore(renovate.json): Remove snapshot filter
  renovate.json
Labels: no milestone

#4445 chore(office-365): bump element template version
  connectors/microsoft/mail/element-templates/microsoft-office365-mail-connector.json
Labels: no milestone, backport release/8.7

#4473 fix(inbound-connector): add to the imap port used in the inbound connector
  connectors/email/src/main/java/io/camunda/connector/email/config/ImapConfig.java
Labels: backport release/8.7

#4465 chore(ms-teams): Remove netty-resolver-dns-native-macos
  connectors/microsoft-teams/pom.xml
  parent/pom.xml
Labels: no milestone
