Repository camunda/connectors, pull requests merged in 2025-02, with the labels that each got.

#3889 other(ci): test commit
  .github/workflows/TEST_FEATURE_BRANCH.yml
  bundle/camunda-saas-bundle/src/test/resources/application.properties
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestZeebeTests.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/resources/application.properties
Labels: no milestone

#3888 fix(template-generator): use server url if description is not found
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/OpenApiOutboundTemplateGenerator.java
  element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
  element-template-generator/openapi-parser/src/test/resources/example-without-server-description.yaml
Labels: no milestone

#3902 other(ci): bring back the old test configuration
  .github/workflows/TEST_FEATURE_BRANCH.yml
Labels: no milestone

#3907 fix(ci): Remove helm manager from renovate config
  renovate.json
Labels: no milestone

#3903 chore(gh-action): Use GH app for backports
  .github/workflows/BACKPORT_PR.yml
Labels: no milestone

#3870 chore(preview-env): update the preview-env teardown workflow
  .github/workflows/PREVIEW-ENV-TEARDOWN.yml
Labels: no milestone

#3919 fix(backport): Use GH app for backports using the right secret path
  .github/workflows/BACKPORT_PR.yml
Labels: no milestone

#3975 chore(deps): support camunda client 8.8.0-SNAPSHOT
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/InboundConnectorRuntimeConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/MeteredInboundCorrelationHandler.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/executable/BatchExecutableProcessor.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImportConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporter.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/metrics/ConnectorMetrics.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/OutboundConnectorRuntimeConfiguration.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/jobhandling/SpringConnectorJobHandler.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorAnnotationProcessor.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/outbound/lifecycle/OutboundConnectorManager.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionImporterTest.java
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/inbound/search/ProcessInstanceClientImplTest.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/InboundConnectorTestConfiguration.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/RuntimeStartupWithConnectorsFromEnvVarsTests.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/outbound/RuntimeStartupWithConnectorsFromSpiTests.java
  connector-sdk/core/src/test/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplierTest.java
  connector-sdk/document/src/main/java/io/camunda/document/reference/CamundaDocumentReferenceImpl.java
  connector-sdk/document/src/main/java/io/camunda/document/store/DocumentCreationRequest.java
  connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/DocumentReferenceModel.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/annotation/jackson/serializer/DocumentSerializer.java
  connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentDeserializationTest.java
  connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/DocumentSerializationTest.java
  connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelDeserializerTest.java
  connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java
  connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelSupplierDeserializerTest.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookActivatedDocumentTests.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/model/HttpCommonResult.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/utils/DocumentHelperTest.java
  connectors/http/rest/README.md
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/client/JdbiJdbcClient.java
  connectors/microsoft-teams/src/main/java/io/camunda/connector/operation/OperationFactory.java
  parent/pom.xml
Labels: no milestone

#3974 fix(github-connector): use correct name of 'release name' property
  connectors/github/element-templates/github-connector.json
Labels: no milestone

#3981 fix(box-connector): Avoid refetching data of deleted items
  connectors/box/element-templates/box-outbound-connector.json
  connectors/box/element-templates/hybrid/box-outbound-connector-hybrid.json
  connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java
  connectors/box/src/main/java/io/camunda/connector/box/BoxUtil.java
  connectors/box/src/main/java/io/camunda/connector/box/model/BoxRequest.java
  connectors/box/src/main/java/io/camunda/connector/box/model/BoxResult.java
Labels: no milestone, backport release/8.7

#3983 fix(docs): remove the mention of make on readme
  README.md
Labels: no milestone

#3987 fix(deps): spring zeebe 8.5.17
  parent/pom.xml
Labels: dependencies, no milestone

#3985 other(local): Disable CORS locally
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java
  bundle/default-bundle/src/test/resources/application-local.properties
Labels: no milestone

#3997 fix(sendgrid-connector): Fix formatting
  connectors/sendgrid/src/test/java/io/camunda/connector/sendgrid/SendGridRequestTest.java
Labels: no milestone

#3996 fix(email-connector): Remove unused dependency
  connectors/email/pom.xml
Labels: no milestone

#4000 fix(license): Fix missing license file
  bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/CorsConfiguration.java
Labels: no milestone

#3894 feat(rest-connector): Add support for proxy auth
  connectors/http/http-base/pom.xml
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/HttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
  connectors/http/http-base/src/test/resources/passwords
  connectors/http/http-base/src/test/resources/squid.conf
Labels: deploy-preview, qa:required, backport release/8.7

#4003 chore(licence-header): Add missing licence header
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
Labels: no milestone

#3872 feat(drive): upload and download file
  connectors/google/google-drive/element-templates/google-drive-outbound-connector.json
  connectors/google/google-drive/element-templates/hybrid/google-drive-outbound-connector-hybrid.json
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveClient.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveFunction.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/GoogleDriveService.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/LoggerProgressListener.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/mapper/DocumentMapper.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/MimeTypeUrl.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/DownloadData.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Resource.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/Type.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/model/request/UploadData.java
  connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveFunctionTest.java
  connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/GoogleDriveServiceTest.java
  connectors/google/google-drive/src/test/java/io/camunda/connector/gdrive/mapper/DocumentMapperTest.java
  connectors/google/google-drive/src/test/resources/requests/file-success-download.json
  connectors/google/google-drive/src/test/resources/requests/file-success-upload.json
  connectors/google/google-drive/src/test/resources/requests/request-fail-test-cases.json
Labels: qa:required, backport release/8.7

#3988 fix(deploy-preview): upgrade 8.7. helm chart to make deploy preview work
  .ci/preview-environments/charts/c8sm/Chart.yaml
  .github/workflows/RELEASE.yaml
Labels: deploy-preview

#4007 Revert "chore: temporarily disable tests in release workflow"
  .github/workflows/RELEASE.yaml
Labels: no milestone

#4008 chore(tests): Fix race condition in ProxyHandler tests
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
Labels: no milestone

#3972 feat(sql): Add JSON support
  connectors/jdbc/pom.xml
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/client/JdbiJdbcClient.java
  connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/client/JdbiJsonHelper.java
  connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationBaseTest.java
  connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/IntegrationTestConfig.java
  connectors/jdbc/src/test/java/io/camunda/connector/jdbc/integration/JdbiJdbcClientIntegrationTest.java
Labels: deploy-preview, qa:required, backport release/8.7

#4049 fix(rest-connector): fix document upload in SaaS
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/JobHandlerContext.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/InboundConnectorContext.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
  connector-sdk/test/src/main/java/io/camunda/connector/test/inbound/InboundConnectorContextBuilder.java
  connector-sdk/test/src/main/java/io/camunda/connector/test/outbound/OutboundConnectorContextBuilder.java
  connectors/aws/aws-bedrock/element-templates/aws-bedrock-outbound-connector.json
  connectors/aws/aws-bedrock/element-templates/hybrid/aws-bedrock-outbound-connector-hybrid.json
  connectors/aws/aws-bedrock/src/main/java/io/camunda/connector/aws/bedrock/BedrockConnectorFunction.java
  connectors/aws/aws-s3/src/main/java/io/camunda/connector/aws/s3/S3ConnectorFunction.java
  connectors/box/src/main/java/io/camunda/connector/box/BoxOperations.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/inbound/PollingManager.java
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
  connectors/google/google-drive/src/main/java/io/camunda/connector/gdrive/mapper/DocumentMapper.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/ExecutionEnvironment.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/HttpService.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionService.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/document/FileResponseHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/HttpServiceTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/TestDocumentFactory.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionResponseTransformer.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/cloudfunction/CloudFunctionServiceTest.java
Labels: backport release/8.7

#4050 feat(rest): Improve http proxy
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/ProxyHandler.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/ProxyHandlerTest.java
Labels: backport release/8.7

#4070 other(CI): Create reopen_support_issues_without_version_label.yml
  .github/workflows/reopen_support_issues_without_version_label.yml
Labels: no milestone

#4121 fix(rest): use contentType from Document metadata when uploading a Document with…
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.7

#4123 other(lint): apply spotless
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
Labels: no milestone

#4130 other(cors): Add CORS configuration for the /inbound-instances endpoint
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/SecurityConfiguration.java
Labels: no milestone

#4119 feat(slack): add attachments support
  connectors/slack/element-templates/hybrid/slack-outbound-connector-hybrid.json
  connectors/slack/element-templates/slack-outbound-connector.json
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/SlackFunction.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/caller/FileUploader.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/mapper/BlocksMapper.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/caller/FileUploaderTest.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/mapper/BlocksMapperTest.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ChatPostMessageDataTest.java
Labels: deploy-preview, qa:required, backport release/8.7

#4138 fix(rest): add support for lists for Parts in a multipart request
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/ApacheRequestBodyBuilder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
Labels: backport release/8.7

#4152 fix(element-template-generato): publish to camunda-nexus for release candidate
  .github/workflows/RELEASE.yaml
Labels: backport release/8.7
