Repository camunda/connectors, pull requests merged in 2025-05, with the labels that each got.

#4724 chore(fix-main): Quick fix for failing LocalConnectorsRuntime on main
  bundle/default-bundle/src/test/resources/application.properties
Labels: no milestone

#4726 test(agentic-ai): update agentic AI e2e test to account for search variable API changes
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AiAgentTests.java
Labels: no milestone

#4677 fix(idp-extraction-connector): substitute GetDocumentAnalysisResponse with GetDocumentTextDetectionResponse
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTask.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
Labels: no milestone

#4717 fix(rest-connector): Fix url encoding to handle edge cases correctly
  connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoder.java
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/builder/parts/UrlEncoderTest.java
Labels: support, backport release/8.6, backport release/8.7

#4760 other(agentic-ai): track 8.8.0-alpha4 compatible templates with new icon
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector-8.8.0-alpha4.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-8.8.0-alpha4-hybrid.json
Labels: no milestone

#4737 fix(idp-extraction-connector): refactor configuration, enabled full connector template generation
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/DocumentAiCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/VertexCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequest.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/AwsProvider.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/DocumentAiRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/GcpProvider.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/ProviderConfig.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/VertexProvider.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/VertexRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/aws/TextExtractionEngineType.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/gcp/DocumentAiRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/gcp/GcpAuthentication.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/gcp/GcpAuthenticationType.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/gcp/GcpRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/gcp/VertexRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/UnstructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/DocumentAiClientSupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/VertexAISupplier.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/GcsUtil.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/DocumentAiCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/VertexCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/DocumentAiClientSupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/VertexAISupplierTest.java
Labels: no milestone

#4766 fix(idp-extraction-connector): added handling of duplicate keys and checkboxes on structured extraction
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/DocumentAiCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractAnalysisTask.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/TextractTextDetectionTask.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/DocumentAiCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
Labels: no milestone

#4779 chore(CODEOWNERS): Add rules for AI & IDP collaborators
  CODEOWNERS
Labels: no milestone

#4781 chore(issues): route new issues to AI team boards based on label.
  .github/workflows/ADD_TO_PROJECT.yml
Labels: no milestone

#4780 chore(inbound): Review activity logs, part 1
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundConnectorContextImpl.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/state/ProcessStateStoreImpl.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/inbound/CorrelationRequest.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaConnectorConsumer.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java
  connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/LogTag.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/LogTag.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqConsumer.java
  connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutable.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/inbound/RabbitMqExecutableLifecycleTest.java
  connectors/webhook/src/main/java/io/camunda/connector/inbound/HttpWebhookExecutable.java
Labels: no milestone, backport release/8.7

#4790 chore(embedding-vector-db): Fix docs link
  connectors/embeddings-vector-database/element-templates/embeddings-vector-database-outbound-connector.json
  connectors/embeddings-vector-database/element-templates/hybrid/embeddings-vector-database-outbound-connector-hybrid.json
  connectors/embeddings-vector-database/src/main/java/io/camunda/connector/EmbeddingsVectorDBFunction.java
Labels: no milestone

#4778 fix(idp-extraction-connector): reversed logic of excluded fields, using inclusion.
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
Labels: no milestone

#4808 feat(agentic-ai): make the OpenAI endpoint + custom headers configurable through properties panel
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/ProviderConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java
Labels: agentic-ai
