Repository camunda/connectors, pull requests merged in 2025-06, with the labels that each got.

#4823 test(agentic-ai): fix e2e tests breaking due to renamed CPT variable method
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/AdHocToolsSchemaTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/Langchain4JAiAgentTests.java
Labels: backport release/8.8

#4755 chore(fossa): check PRs for newly introduced license issues
  .github/workflows/CHECK_LICENSES.yml
Labels: no milestone

#4826 refactor(agentic-ai): implement JSON schema de(-serializing) as Jackson de(-serializer)
  connectors/agentic-ai/pom.xml
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/JsonSchemaConstants.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/Langchain4JAiFrameworkAdapter.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/configuration/AgenticAiLangchain4JFrameworkConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementDeserializer.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementModule.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementSerializer.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverter.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverterImpl.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/jsonschema/JsonSchemaElementModuleTest.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/tool/ToolSpecificationConverterTest.java
  connectors/agentic-ai/src/test/resources/jsonschema/mcp-server-everything-tools-list.json
  connectors/agentic-ai/src/test/resources/jsonschema/mcp-server-filesystem-tools-list.json
Labels: no milestone, agentic-ai

#4828 fix(agentic-ai): fix chat message converter not properly handling AI responses without text content
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterImpl.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterTest.java
Labels: backport release/8.8, agentic-ai

#4832 fix(camunda-client): Fix config path env variable
  bundle/camunda-saas-bundle/Dockerfile
  bundle/default-bundle/Dockerfile
  connector-runtime/connector-runtime-application/Dockerfile
Labels: no milestone

#4836 fix(client-config): Fix client credentials auth cache path env
  bundle/camunda-saas-bundle/Dockerfile
  bundle/default-bundle/Dockerfile
  connector-runtime/connector-runtime-application/Dockerfile
Labels: no milestone, backport release/8.7

#4841 fix(aws-auth): Prohibit usage of AWS default credential chain in SaaS…
  bundle/camunda-saas-bundle/Dockerfile
  connectors/aws/aws-base/pom.xml
  connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/model/impl/AwsBaseRequest.java
  connectors/aws/aws-base/src/test/java/io/camunda/connector/aws/AwsBaseRequestTest.java
Labels: no milestone

#4840 fix(aws-auth): Prohibit usage of AWS default credential chain in SaaS…
  bundle/camunda-saas-bundle/Dockerfile
  connectors/aws/aws-base/pom.xml
  connectors/aws/aws-base/src/main/java/io/camunda/connector/aws/model/impl/AwsBaseRequest.java
  connectors/aws/aws-base/src/test/java/io/camunda/connector/aws/AwsBaseRequestTest.java
Labels: no milestone

#4850 other(local): update local application properties
  bundle/default-bundle/src/test/resources/application.properties
Labels: no milestone

#4853 docs(agentic-ai): update AI Agent connector description to include alpha version compatibility
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/AiAgentFunction.java
Labels: no milestone, agentic-ai

#4818 feat(intrinsic-function): Adding new intrinsic function for retrieving JSON data
  bundle/default-bundle/src/test/resources/application.properties
  connector-sdk/document/pom.xml
  connector-sdk/document/src/main/java/io/camunda/intrinsic/functions/GetJsonFunction.java
  connector-sdk/document/src/main/resources/META-INF/services/io.camunda.intrinsic.IntrinsicFunctionProvider
  connector-sdk/document/src/test/java/io/camunda/intrinsic/functions/GetJsonFunctionTest.java
Labels: deploy-preview, no milestone, qa:required, backport release/8.7

#4870 other(docs): update the LocalConnectorRuntime readme
  bundle/default-bundle/README.md
Labels: no milestone

#4872 fix(CustomApacheHttpClientTest): Set max file descriptors in squid
  connectors/http/http-base/src/test/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClientTest.java
  connectors/http/http-base/src/test/resources/squid.conf
Labels: kind:bug, backport release/8.6, no milestone, backport release/8.7

#4909 fix(deps): pin grpc version
  parent/pom.xml
Labels: no milestone

#4900 feat(32376): Switch RELEASE.yaml to use camunda/infra-global-github-actions/previous-version GHA
  .github/workflows/RELEASE.yaml
  .github/workflows/scripts/prev_tag-test.sh
  .github/workflows/scripts/prev_tag.sh
Labels: no milestone

#4919 test(agentic-ai): reduce e2e document test cases
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java
Labels: no milestone, agentic-ai

#4897 fix(self-managed): fix SM so that inbound polling can be disabled again
  connector-runtime/connector-runtime-application/src/main/java/io/camunda/connector/runtime/app/ConnectorRuntimeApplication.java
Labels: kind:bug, support, deploy-preview, qa:required, version:8.7.4

#4916 chore(RabbitMQ): bump to version 4.1.1
  connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/BaseRabbitMqTest.java
  connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqInboundStartEventTests.java
  connectors-e2e-test/connectors-e2e-test-rabbitmq/src/test/java/io/camunda/connector/e2e/RabbitMqOutboundTests.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/BaseTest.java
  connectors/rabbitmq/src/test/java/io/camunda/connector/rabbitmq/integration/RabbitMqIntegrationTest.java
Labels: no milestone

#4771 fix(idp-extraction-connector): added table content support idp for structured extraction
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/DocumentAiCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResponse.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResult.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/DocumentAiCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/PollingTextractCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
Labels: no milestone

#4942 feat(bundle): use latest config property
  bundle/camunda-saas-bundle/README.md
  bundle/camunda-saas-bundle/src/main/resources/application.properties
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/InboundInstancesSecurityConfigurationTest.java
  bundle/camunda-saas-bundle/src/test/java/io/camunda/connector/runtime/saas/SecurityConfigurationTest.java
  bundle/default-bundle/README.md
  bundle/default-bundle/src/main/resources/application.properties
  bundle/default-bundle/src/test/resources/application.properties
  connector-runtime/README.md
  connector-runtime/connector-runtime-application/README.md
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/inbound/InboundIntermediateConnectorContextImpl.java
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/importer/ProcessDefinitionSearch.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/resources/application.properties
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookActivatedDocumentTests.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookNotActivatedDocumentTests.java
  connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java
  connectors/slack/src/test/resources/application.properties
Labels: no milestone

#4961 chore(deployment): Fix deployment name on central
  parent/pom.xml
Labels: backport release/8.4, no milestone

#4967 chore(deployment): Undo setting name manually
  parent/pom.xml
Labels: backport release/8.4, no milestone

#4975 test(agentic-ai): temporarily disable flaky e2e tests involving document conversation memory storage
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMemoryStorageTests.java
Labels: no milestone

#4979 refactor(agentic-ai): rename alpha to experimental in MCP connectors
  connectors/agentic-ai/element-templates/agenticai-mcp-client-outbound-connector.json
  connectors/agentic-ai/element-templates/agenticai-mcp-remote-client-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-mcp-client-outbound-connector-hybrid.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-mcp-remote-client-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpClientFunction.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/mcp/client/McpRemoteClientFunction.java
Labels: no milestone, agentic-ai

#4976 test(agentic-ai): fix flaky e2e document handling tests
  connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentMemoryStorageTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentToolCallingTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/Langchain4JAiAgentUserPromptDocumentsTests.java
Labels: agentic-ai
