Repository camunda/connectors, pull requests merged in 2025-09, with the labels that each got.

#5331 fix: revert "deps(vector-db): bump langchain4j to 1.4.0 (#5330)"
  connectors/embeddings-vector-database/src/main/java/io/camunda/connector/embeddingstore/AzureVectorStoreFactory.java
  connectors/embeddings-vector-database/src/test/java/io/camunda/connector/embeddingstore/DefaultEmbeddingStoreFactoryTest.java
  parent/pom.xml
Labels: agentic-ai

#5311 feat(agentic-ai): add an OpenAI compatible provider
  connectors/agentic-ai/element-templates/agenticai-aiagent-job-worker.json
  connectors/agentic-ai/element-templates/agenticai-aiagent-outbound-connector.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-job-worker-hybrid.json
  connectors/agentic-ai/element-templates/hybrid/agenticai-aiagent-outbound-connector-hybrid.json
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/OpenAiCompatibleProviderConfiguration.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/provider/ProviderConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatModelFactoryTest.java
Labels: agentic-ai

#5339 other(logging): replace error logs with debug for saas auth type
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/AuthPropertiesNotPresentCondition.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ProcessDefinitionImportHealthIndicator.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/ZeebeHealthIndicator.java
Labels: no milestone

#5354 chore(ci): Fix QA workflow
  .github/workflows/ENFORCE_QA_APPROVAL.yml
Labels: no milestone

#5336 chore(local-setup): Fix rest address
  bundle/default-bundle/src/test/resources/application-local.properties
Labels: no milestone

#5358 fix(logging): log job completion at INFO level (#5356)
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandler.java
Labels: no milestone

#5345 fix(agentic-ai): fix system prompts in examples
  connectors/agentic-ai/examples/ai-agent-chat-mcp/ai-agent-ahsp-chat-with-mcp.bpmn
  connectors/agentic-ai/examples/ai-agent-chat-mcp/ai-agent-chat-with-mcp.bpmn
  connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-ahsp-chat-with-tools.bpmn
  connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
  connectors/agentic-ai/examples/fraud-detection/fraud-detection-process.bpmn
Labels: no milestone, agentic-ai

#5373 other(build): stop publishing bundle jars to central
  bundle/camunda-saas-bundle/pom.xml
  bundle/default-bundle/pom.xml
  connector-runtime/connector-runtime-application/pom.xml
Labels: backport release/8.8

#5374 fix(agentic-ai): fix service task based examples to define toolCallResult as local variable
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/jobworker/BaseL4JAiAgentJobWorkerTest.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/outboundconnector/BaseL4JAiAgentConnectorTest.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors-mcp.bpmn
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
  connectors/agentic-ai/examples/ai-agent-chat-mcp/ai-agent-chat-with-mcp.bpmn
  connectors/agentic-ai/examples/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
  connectors/agentic-ai/examples/fraud-detection/fraud-detection-process.bpmn
Labels: agentic-ai

#5406 docs(agentic-ai): update example BPMN files with latest template applied
  connectors/agentic-ai/examples/ad-hoc-tools-schema/ad-hoc-tools-schema-resolver.bpmn
  connectors/agentic-ai/examples/ai-agent/ad-hoc-sub-process/ai-agent-chat-mcp/ai-agent-chat-with-mcp.bpmn
  connectors/agentic-ai/examples/ai-agent/ad-hoc-sub-process/ai-agent-chat-with-tools/ai-agent-chat-with-tools.bpmn
  connectors/agentic-ai/examples/ai-agent/service-task/fraud-detection/fraud-detection-service-task-process.bpmn
Labels: agentic-ai

#5404 fix(agentic-ai): Make user prompt mandatory
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/request/PromptConfiguration.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/model/request/PromptConfigurationTest.java
Labels: agentic-ai

#5420 other(debug): Add support agents to the allowed users for manage and run
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/security/InboundInstancesSecurityConfiguration.java
  bundle/camunda-saas-bundle/src/main/resources/application.properties
Labels: no milestone, backport release/8.7

#5422 feat(external-document): Add new external document type
  connector-commons/http-client/src/main/java/io/camunda/connector/http/client/client/apache/CustomApacheHttpClient.java
  connector-commons/http-client/src/main/java/io/camunda/connector/http/client/client/apache/HttpCommonResultResponseHandler.java
  connector-commons/http-client/src/main/java/io/camunda/connector/http/client/document/FileResponseHandler.java
  connector-commons/http-client/src/main/java/io/camunda/connector/http/client/document/HttpHeaderFilenameResolver.java
  connector-commons/http-client/src/main/java/io/camunda/connector/http/client/model/HttpClientRequest.java
  connector-commons/http-client/src/test/java/io/camunda/connector/http/client/client/apache/HttpClientResultResponseHandlerTest.java
  connector-commons/http-client/src/test/java/io/camunda/connector/http/client/document/HttpHeaderFilenameResolverTest.java
  connector-runtime/connector-runtime-core/pom.xml
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/document/DocumentFactoryImpl.java
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/document/ExternalDocument.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/document/ExternalDocumentTest.java
  connector-runtime/connector-runtime-core/src/test/resources/testpdf.pdf
  connector-runtime/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/DocumentReferenceModel.java
  connector-sdk/core/src/main/java/io/camunda/connector/api/document/DocumentReference.java
Labels: deploy-preview, qa:required

#5426 fix(agentic-ai): filter chat response metadata stored as part of conversation
  connectors/agentic-ai/AI_AGENT.md
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterImpl.java
  connectors/agentic-ai/src/main/java/io/camunda/connector/agenticai/aiagent/model/AgentResponse.java
  connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/ChatMessageConverterTest.java
Labels: agentic-ai

#5444 chore(refactoring): Remove empty dynamodb e2e test module
  connectors-e2e-test/connectors-e2e-test-aws/connectors-e2e-test-aws-dynamodb/pom.xml
  connectors-e2e-test/connectors-e2e-test-aws/pom.xml
Labels: no milestone, backport release/8.7

#5438 chore(ci): rename next release branch to alpha; simplify renovate config
  .github/workflows/CREATE_RELEASE_BRANCH.yml
  renovate.json
Labels: no milestone

#5446 fix(agentic-ai): adapt e2e tests for updated response handling (not explicitely setting TEXT)
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/jobworker/L4JAiAgentJobWorkerResponseHandlingTests.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/outboundconnector/L4JAiAgentConnectorResponseHandlingTests.java
  connectors/agentic-ai/AI_AGENT.md
Labels: agentic-ai

#5454 fix(idp-extraction-connector): fixed idp unstructured extraction malformed json response
  connectors/idp-extraction/pom.xml
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/AzureAiFoundryCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/BedrockCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/VertexCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/UnstructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/utils/StringUtil.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/AzureAiFoundryCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/VertexCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/utils/StringUtilTest.java
Labels: no milestone

#5455 ci(nightly): fix the uploaded test result names
  .github/workflows/NIGHTLY_E2E.yml
Labels: no milestone

#5456 ci(nightly): fix the uploaded test result names
  .github/workflows/NIGHTLY_E2E.yml
Labels: no milestone
