Repository camunda/connectors, pull requests merged in 2025-04, with the labels that each got.

#4490 chore: move to 8.4.17 spring zeebe
  connectors-e2e-test/connectors-e2e-test-base/pom.xml
  parent/pom.xml
Labels: no milestone

#4502 Move to zeebe client 8.5.16
  parent/pom.xml
Labels: no milestone

#4499 fix(config): failsafe cluster id prop in saas
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConfiguration.java
Labels: backport release/8.8

#4507 chore(renovate): Renovate disable major minor camunda updates
  renovate.json
Labels: no milestone

#4530 chore(renovate): Fix io.camunda matching
  renovate.json
Labels: no milestone

#4546 fix(json): Enhance json binding for single element arrays
  connector-sdk/core/src/main/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplier.java
  connector-sdk/core/src/test/java/io/camunda/connector/api/json/ConnectorsObjectMapperSupplierTest.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DocumentDeserializer.java
  connectors/google/google-gemini/src/test/java/io/camunda/connector/gemini/mapper/PromptsMapperTest.java
  connectors/google/google-gemini/src/test/resources/prompts_with_wrong_value_type.json
Labels: backport release/8.7

#4559 chore(renovate): Add grouping and schedule to renovate config
  renovate.json
Labels: no milestone

#4565 chore(deps): pin httpcore5-h2 due to an incompatibility in camunda client
  parent/pom.xml
Labels: no milestone

#4563 chore(ci): Adjust link in bump docs workflow
  .github/workflows/TEST_FEATURE_BRANCH.yml
  .github/workflows/scripts/collect_all_element_template_docs_links.sh
Labels: no milestone

#4519 other(e2e): fix E2E tests
  bundle/camunda-saas-bundle/src/test/resources/application.properties
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/resources/application.properties
  connectors-e2e-test/connectors-e2e-test-base/src/main/resources/application.properties
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/HttpTests.java
  connectors-e2e-test/connectors-e2e-test-http/src/test/java/io/camunda/connector/e2e/WebhookActivatedDocumentTests.java
Labels: no milestone

#4575 chore(renovate): Add ignore of replacement updates and migrate outdated rule
  renovate.json
Labels: no milestone

#4588 chore(renovate): Increase pr hourly limit to 10
  renovate.json
Labels: no milestone

#4591 chore: move camunda libraries to 8.7
  parent/pom.xml
Labels: no milestone

#4600 chore(dependency): Remove camunda-java dependency
  parent/pom.xml
Labels: backport release/8.8

#4593 chore(fossa): extend integration to stable branches and tags
  .fossa.yml
  .github/workflows/CHECK_LICENSES.yml
Labels: backport release/8.3, backport release/8.4, backport release/8.5, backport release/8.6, no milestone, backport release/8.7, backport release/8.8

#4611 fix(slack-connector): Make the slack connector works as it was before, with document features
  connector-sdk/core/src/main/java/io/camunda/connector/api/error/ConnectorInputException.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/caller/FileUploader.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/mapper/BlockBuilder.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/mapper/BlocksMapper.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/ChatPostMessageData.java
  connectors/slack/src/main/java/io/camunda/connector/slack/outbound/model/MessageType.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/mapper/BlockBuilderTest.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/mapper/BlocksMapperTest.java
  connectors/slack/src/test/java/io/camunda/connector/slack/outbound/model/ChatPostMessageDataTest.java
Labels: backport release/8.7

#4609 chore(plugins): Add requirePluginVersions rule
  connectors/kafka/pom.xml
  connectors/webhook/pom.xml
  parent/pom.xml
Labels: no milestone

#4535 fix(idp-extraction-connector): add support for idp form extraction
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/pom.xml
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunction.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/DocumentAiCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/caller/PollingTextractCaller.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionType.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResponse.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResult.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/DocumentAIProvider.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/DocumentAiRequestConfiguration.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/providers/ProviderConfig.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/ExtractionService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/UnstructuredService.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/supplier/DocumentAiClientSupplier.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/ExtractionConnectorFunctionTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/caller/DocumentAiCallerTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/UnstructuredServiceTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/suppliers/DocumentAiClientSupplierTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/util/ExtractionTestUtils.java
Labels: no milestone

#4621 fix(config): remove default address property values on 8.7
  bundle/default-bundle/src/main/resources/application.properties
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretProvider.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
Labels: no milestone

#4622 fix(config): remove default address property values
  bundle/default-bundle/src/main/resources/application.properties
  connector-runtime/connector-runtime-application/src/main/resources/application.properties
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/secret/ConsoleSecretProvider.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
Labels: no milestone

#4653 fix(webhook): Error coming from zeebe are now managed properly
  connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/webhook/InboundWebhookRestController.java
  connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/inbound/WebhookControllerTestExceptionZeebeTests.java
Labels: backport release/8.6, backport release/8.7

#4633 fix(idp-extraction-connector): add original keys as output to the structured extraction
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/StructuredExtractionResult.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
Labels: no milestone

#4657 feat(Email-outbound): [Email-outbound] Add generated Message-ID in response for tracking…
  connectors/email/src/main/java/io/camunda/connector/email/client/jakarta/outbound/JakartaEmailActionExecutor.java
  connectors/email/src/main/java/io/camunda/connector/email/response/SendEmailResponse.java
Labels: deploy-preview

#4630 fix(idp-extraction-connector): add renameMappings input
  connectors/idp-extraction/element-templates/hybrid/hybrid-idp-extraction-outbound-connector-hybrid.json
  connectors/idp-extraction/element-templates/idp-extraction-outbound-connector.json
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/model/ExtractionRequestData.java
  connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/service/StructuredService.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/service/StructuredServiceTest.java
  connectors/idp-extraction/src/test/java/io/camunda/connector/idp/extraction/util/ExtractionTestUtils.java
Labels: no milestone

#4498 feat(element-template-generator): Add all auth sections if no security scheme provided by openapi scheme
  element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/HttpAuthentication.java
  element-template-generator/http-dsl/src/main/java/io/camunda/connector/generator/dsl/http/PropertyUtil.java
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/SecurityUtil.java
  element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/SecurityUtilTest.java
Labels: deploy-preview, qa:required

#4654 chore(renovate): Match all release branches with regex
  renovate.json
Labels: no milestone

#4666 other(tests): fix E2E test
  connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/instances/service/DefaultInstanceForwardingServiceIntegrationTest.java
Labels: no milestone

#4673 chore(dependency): Upgrade classgraph dependency to fix CVE
  connectors/kafka/pom.xml
Labels: backport release/8.6

#4678 other(manage-and-run): fix pods URL using HTTP not HTTPS
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/http/DefaultInstancesUrlBuilder.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/http/DefaultInstancesUrlBuilderTest.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/http/InstanceForwardingHttpClientTest.java
Labels: no milestone, backport release/8.7

#4680 fix(intrinsic-functions): introduce guardrails for intrinsic functions
  connector-runtime/connector-runtime-core/src/main/java/io/camunda/connector/runtime/core/ConnectorHelper.java
  connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/ConnectorHelperTest.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/JacksonModuleDocumentDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/AbstractDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ByteArrayDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DeserializationUtil.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/DocumentDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/InputStreamDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/IntrinsicFunctionObjectResultDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/ObjectDeserializer.java
  connector-sdk/jackson-datatype-document/src/main/java/io/camunda/connector/document/jackson/deserializer/StringDeserializer.java
  connector-sdk/jackson-datatype-document/src/test/java/io/camunda/connector/document/jackson/IntrinsicFunctionDeserializationTest.java
Labels: backport release/8.7

#4681 test(agentic-ai): fix e2e test flakiness
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/BaseAgenticAiTest.java
  connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/resources/agentic-ai-connectors.bpmn
  connectors-e2e-test/connectors-e2e-test-base/src/main/java/io/camunda/connector/e2e/ZeebeTest.java
Labels: no milestone, backport release/8.8

#4679 fix(open-api): fix open api issue on type
  element-template-generator/openapi-parser/src/main/java/io/camunda/connector/generator/openapi/util/ParameterUtil.java
  element-template-generator/openapi-parser/src/test/java/io/camunda/connector/generator/openapi/ExampleTest.java
  element-template-generator/openapi-parser/src/test/resources/example-without-type.json
Labels: backport release/8.7

#4691 ci(helm): rename chart dir from alpha to 8.8
  .github/workflows/helm-git-refs.json
Labels: no milestone

#4695 chore(hugging-face): bring the runtime to 8.5 instead of 8.6 for version 2
  connectors/hugging-face/element-templates/hugging-face-connector.json
Labels: no milestone

#4199 feat(message): Publish message outbound connector
  bundle/camunda-saas-bundle/src/main/java/io/camunda/connector/runtime/saas/SaaSConnectorRuntimeApplication.java
  bundle/default-bundle/pom.xml
  bundle/pom.xml
  connectors-e2e-test/connectors-e2e-test-message/pom.xml
  connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java
  connectors-e2e-test/pom.xml
  connectors/camunda-message/README.md
  connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-intermediate-throw-event-hybrid.json
  connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-message-end-event-hybrid.json
  connectors/camunda-message/element-templates/hybrid/hybrid-send-message-connector-send-task-hybrid.json
  connectors/camunda-message/element-templates/send-message-connector-intermediate-throw-event.json
  connectors/camunda-message/element-templates/send-message-connector-message-end-event.json
  connectors/camunda-message/element-templates/send-message-connector-send-task.json
  connectors/camunda-message/pom.xml
  connectors/camunda-message/src/main/java/io/camunda/connector/message/SendMessageConnectorFunction.java
  connectors/camunda-message/src/main/java/io/camunda/connector/message/SendMessageRequest.java
  connectors/camunda-message/src/main/java/io/camunda/connector/runtime/app/ZeebeClientContext.java
  connectors/camunda-message/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction
  connectors/camunda-message/src/main/resources/send.svg
  connectors/camunda-message/src/test/resources/correlate-message-process.bpmn
  connectors/camunda-message/src/test/resources/correlation-failed-process.bpmn
  connectors/camunda-message/src/test/resources/receive-message-process.bpmn
  connectors/camunda-message/src/test/resources/send-message-connector-test-process.bpmn
  connectors/pom.xml
Labels: qa:required, backport release/8.7

#4703 other(e2e): fix end tests
  connectors-e2e-test/connectors-e2e-test-message/src/test/java/io/camunda/connector/e2e/MessageTests.java
Labels: no milestone, backport release/8.7, backport release/8.8
